-- 멤버구분
DROP TABLE membergroup CASCADE CONSTRAINTS;

-- 회원
DROP TABLE Member CASCADE CONSTRAINTS;

-- 질문항목
DROP TABLE question CASCADE CONSTRAINTS;

-- 카테고리분류
DROP TABLE categorygroup CASCADE CONSTRAINTS;

-- 카테고리
DROP TABLE category CASCADE CONSTRAINTS;

-- 클래스
DROP TABLE Class CASCADE CONSTRAINTS;

-- 클래스예약
DROP TABLE booking CASCADE CONSTRAINTS;

-- 스케줄
DROP TABLE classschedule CASCADE CONSTRAINTS;

-- 업로드파일
DROP TABLE upfile CASCADE CONSTRAINTS;
-- 클래스Q&A답변
DROP TABLE classqnarepay;



-- 클래스Q&A게시판
DROP TABLE classqnaboard;

-- 클래스후기게시판
DROP TABLE classboard;

-- 게시판분류
DROP TABLE boardgroup CASCADE CONSTRAINTS;
-- 쪽지관리
DROP TABLE messagemaga;

-- 쪽지
DROP TABLE message;
--rollback

-- 공지사항
DROP TABLE noticeboard;

-- 이용안내
DROP TABLE useboard;

-- 찜하기
DROP TABLE shoppingbasket;

-- 결제
DROP TABLE payment CASCADE CONSTRAINTS;

-- 결제취소
DROP TABLE paymentcancel;

-- 관리자메인관리
DROP TABLE operator;

--관심호스트
DROP TABLE follow;

--신고NOTIFY 
DROP TABLE NOTIFY;


DROP SEQUENCE BOARDGROUP_seq;
DROP SEQUENCE BOOKING_seq;
DROP SEQUENCE CATEGORY_seq;
DROP SEQUENCE CATEGORYGROUP_seq;
DROP SEQUENCE CLASS_seq;
DROP SEQUENCE CLASSBOARD_seq;
DROP SEQUENCE CLASSQNABOARD_seq;
DROP SEQUENCE CLASSQNAREPAY_seq;
DROP SEQUENCE CLASSSCHEDULE_seq;
DROP SEQUENCE MEMBER_seq;
DROP SEQUENCE MEMBERGROUP_seq;
DROP SEQUENCE MESSAGE_seq;
DROP SEQUENCE MESSAGEMAGA_seq;
DROP SEQUENCE NOTICEBOARD_seq;
DROP SEQUENCE OPERATOR_seq;
DROP SEQUENCE PAYMENT_seq;
DROP SEQUENCE PAYMENTCANCEL_seq;
DROP SEQUENCE QUESTION_seq;
DROP SEQUENCE SHOPPINGBASKET_seq;
DROP SEQUENCE UPFILE_seq;
DROP SEQUENCE USEBOARD_seq;
DROP SEQUENCE FOLLOW_seq;